### ISSUE TITLE
Hide the notification icon (bell) in the github.com topbar

### ISSUE THREAD

**Issue by mpenkov** [janpio/github-hide-notifications#10]
This bell has a blue dot next to it when there are existing notifications.

It can be a bit distracting. Is it possible to hide it altogether? The xpath is:

```
/html/body/div[1]/header/div[5]/a/svg
```

and the code looks like this:

```
<svg class="octicon octicon-bell" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M14 12v1H0v-1l.73-.58c.77-.77.81-2.55 1.19-4.42C2.69 3.23 6 2 6 2c0-.55.45-1 1-1s1 .45 1 1c0 0 3.39 1.23 4.16 5 .38 1.88.42 3.66 1.19 4.42l.66.58H14zm-7 4c1.11 0 2-.89 2-2H5c0 1.11.89 2 2 2z"></path></svg>
```

Thanks for the cool extension!

**Comment by janpio** [comment]
Hey @mpenkov, thanks for your comment.

The extension could totally do that, but to be honest I am hesitant to add it. Not all users want it, adding an option makes everything a lot more complicated - and most importantly I think using an ad blocker like uBlock Origin is the much better too for that. I just right click the blue dot and select "Hide Element" to get rid of it on any new computer I start working on.

Does that make sense?

**Comment by mpenkov** [comment]
It's up to you, but from my novice POV, this seems to be within the domain of the problem your extension is trying to solve. I agree that not all people would want this, so this would be an opt-in option.

If nobody else wants this, though, I agree: using uBlock is the simplest solution.
